---
title: "testing_algs"
author: "Fran Beresford Lynsie Warr"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("mvtnorm")
library(mvtnorm)
library(ggplot2)
setwd("~/230_FINAL_PROJ")
source("algorithm_function_no_par.R")
source("optim_abc.R")
```

## R Markdown

Start by simulating spatial data. 

```{r cars}
# Simulate the data

xycoords <- seq(from=0,to=1,length=5)
allcoords <- expand.grid(xycoords,xycoords)
nlocs <- nrow(allcoords)

# make the covariance function for the GPs
true.range <- .4
true.sigma2 <- 2
distmat <- as.matrix(dist(allcoords,diag=TRUE,upper=TRUE))
Sigma <- true.sigma2 * exp(-true.range*distmat)

# simulate the GP at each location
ys <- chol(Sigma)%*%rnorm(nlocs) # leave it at mean=0
  
# simulate poisson process based on that
ts <- runif(nlocs,min=1,max=10) # observation durations
beta <- .5 # will not be differentiated from the mean of the GP,so use mean=0
lambdas <- ts*exp(ys+beta)

Xs <- rpois(nlocs,lambdas)

# plot heat map of the data
plotdata <- data.frame(allcoords,Xs,ys)
ggplot(plotdata, aes(Var1, Var2, fill= Xs)) + 
  geom_tile()

# we want to model y, etc from above data to compare to true surface
ggplot(plotdata, aes(Var1, Var2, fill= ys)) + 
  geom_tile()
```

## testing algorithm code 

You can also embed plots, for example:

```{r pressure, echo=FALSE}
mcmc_alg_meth_1(num_locs=nlocs, num_its= 10, dist_mat = distmat, X=Xs, t_cov= ts, beta_prop_sigma = 0.5, theta_prop_sigma = c(0.5, 0.5))


num_locs = nlocs 
num_its = 10 
dist_mat = distmat
X = Xs
t_cov = ts 
beta_prop_sigma = 0.5
theta_prop_sigma <- c(0.5, 0.5) 
t= 2



```



















